on:
  push:
    tags:
      - '*'

jobs:

  test:

    name: ${{ matrix.lisp }}

    strategy:
      matrix:
        lisp: [sbcl]
        os: [ubuntu-20.04]
        version: [v0.1.0]
        core_name: [htss-${{ matrix.os }}-${{ github.ref_name }}.gz]
    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v2

    - name: Update $PATH
      run: |
        echo $PATH
        echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
    - name: Check $PATH
      run: echo $PATH

    - name: Download implementation
      env:
        LISP: ${{ matrix.lisp }}
      run: |
        pwd
        ls -l
        bash <(curl -s https://raw.githubusercontent.com/digikar99/lisp-travis-lite/master/run.sh)

    - name: Prepare htss
      run: cl --eval '(push "./" ql:*local-project-directories*)' --eval '(ql:quickload "hunchentoot-simple-server")' --eval "(asdf:oos 'asdf:program-op :hunchentoot-simple-server)"


    - name: Rename htss
      run: mv htss ${{ matrix.core_name }}

    - name: Compress htss
      run: gzip htss

    - name: Upload htss
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.core_name }}
        path: ${{ matrix.core_name }}

    - name: Publish htss
      uses: SierraSoftworks/gh-releases@v1.0.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        overwrite: 'true'
        files: ${{ matrix.core_name }}
